name: medconb
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - argon2-cffi
    - ariadne==0.26.*
    - authlib
    - confuse
    - pandas
    - plyse==1.0.3
    - psycopg2-binary
    - pydantic==2.*
    - PyJWT==2.8.0
    - pyparsing==2.4.0
    - pyyaml
    - redis
    - sqlalchemy==2.0.*
    - starlette
    - starlette-context
    - uvicorn
  # dev dependencies:
    - black
    - devtools
    - httpx
    - ipython
    - isort==5.*
    - mccabe
    - mypy==1.10.1  # can't upgrade mypy above 1.10.1, because of sqlalchemy (waiting for v2.1)
    - pycodestyle
    - pyflakes
    - pytest
    - pytest-asyncio
    - pytest-cov
    - pylama
    - radon
    - requests  # integration tests with starlette TestClient
    - sqlalchemy[mypy]
    - types-PyYAML
    - types-redis
    - types-requests
    # doc dependencies:
    - mkdocstrings
    - mkdocstrings[python]
    - mkdocs-glightbox
    - mkdocs-literate-nav
    - mkdocs-material
# conda env remove -n medconb
# conda env create -n medconb -f environment.dev.yml
# conda env update -n medconb -f environment.dev.yml
# conda env export -n medconb --no-builds > environment.dev.fixed.yml
# remove `appnope` (mac only) requirement!
